<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
		<ApplicationIcon>Assets\icon.ico</ApplicationIcon>
		<Version>2.0.8</Version>
		<InformationalVersion>2.0.8</InformationalVersion>
		<ReleaseDate>08.06.2026 05:05 CET</ReleaseDate>
	</PropertyGroup>
	
	<ItemGroup>
		<AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
			<_Parameter1>ReleaseDate</_Parameter1>
			<_Parameter2>$(ReleaseDate)</_Parameter2>
		</AssemblyAttribute>
	</ItemGroup>
	
	<ItemGroup>
		<AvaloniaResource Include="Assets\**" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="Assets\icon.ico" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" Version="12.1.0" />
		<PackageReference Include="Avalonia.Desktop" Version="12.1.0" />
		<PackageReference Include="Avalonia.Svg.Skia" Version="11.3.0" />
		<PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.0" />
		<PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.0" />
		<!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
		<PackageReference Include="Avalonia.Diagnostics" Version="11.3.18">
			<IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
			<PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
		</PackageReference>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		<PackageReference Include="MessageBox.Avalonia" Version="12.0.0" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="11.0.0-preview.5.26302.115" />
		<PackageReference Include="Velopack" Version="1.2.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ClientRenderer\ClientRenderer.csproj" />
		<ProjectReference Include="..\DanserWrapper\DanserWrapper.csproj" />
		<ProjectReference Include="..\ExperimentalRendererWrapper\ExperimentalRendererWrapper.csproj" />
	</ItemGroup>
</Project>
